name: Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'chart/**'
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    uses: Flaminel/umbrella-workflows-test/.github/workflows/chart.install.yml@main
    with:
      githubContext: ${{ toJSON(github) }}
      useChartMuseum: false
    secrets:
      SECRETS_TOKEN: ${{ secrets.SECRETS_TOKEN }}