name: Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'chart/**'
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    uses: flmorg/universal-workflows/.github/workflows/chart.install.yml@main
    with:
      githubContext: ${{ toJSON(github) }}
      useChartMuseum: false
    secrets: inherit
